version: "3.9"  # optional since v1.27.0

services:
  web_api:
    image: web_api
    container_name: web_api
    build:
      context: .
      dockerfile: /Web.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_started
    environment:
      - WeatherForecastsContext__HOST=sql_server_2022
      - WeatherForecastsContext__UserId=SA
      - WeatherForecastsContext__PASSWORD=A&VeryComplex123Password

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server_2022
    hostname: sql_server_2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433"
    volumes:
      - ./Web.Api/Data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
